Dende\Calendar\Domain\Calendar\Event\Occurrence:
  type: mappedSuperclass
  table: occurrences
  repositoryClass: Dende\CalendarBundle\Repository\ORM\OccurrenceRepository

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  id:
    id:
      type: integer
      generator: { strategy: auto }

  embedded:
    occurrenceData:
      class: Dende\Calendar\Domain\Calendar\Event\Occurrence\OccurrenceData
      columnPrefix: false
    occurrenceId:
      class: Dende\Calendar\Domain\Calendar\Event\Occurrence\OccurrenceId
      columnPrefix: occurrence_

  indexes:
    index_dende_occurrences_dates:
      columns:
        - startDate
        - endDate

  manyToOne: # occurrence is the owning side!
    event:
      targetEntity: Dende\Calendar\Domain\Calendar\Event
      inversedBy: occurrences
      cascade: [all]
      joinColumns:
        EventId:
          name: event_id
          referencedColumnName: id

  fields:
    modified:
      type: boolean
