Dende\Calendar\Domain\Calendar\Event:
  type: entity
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: discriminator
    type: string
  discriminatorMap:
    bundle: Dende\Calendar\Domain\Calendar\Event
  table: events
  repositoryClass: Dende\CalendarBundle\Repository\ORM\EventRepository

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  id:
    id:
      type: integer
      generator: { strategy: auto }

  indexes:
    index_dende_events_dates:
      columns:
        - startDate
        - endDate

  embedded:
    type:
      class: Dende\Calendar\Domain\Calendar\Event\EventType
      columnPrefix: false

    eventId:
      class: Dende\Calendar\Domain\Calendar\Event\EventId
      columnPrefix: event_

    eventData:
      class: Dende\Calendar\Domain\Calendar\Event\EventData
      columnPrefix: false

  manyToOne:  # event is the owning side!
    calendar:
      targetEntity: Dende\Calendar\Domain\Calendar
      inversedBy: events
      cascade: [all]
      joinColumns:
        CalendarId:
          name: calendar_id
          referencedColumnName: id
          onDelete: SET NULL

  oneToMany:
    occurrences:
      targetEntity: Dende\Calendar\Domain\Calendar\Event\OccurrenceInterface
      mappedBy: event
      cascade: [all]

  fields:
    deletedAt:
      type: datetime
      nullable: true
