Dende\Calendar\Domain\Calendar:
  type: entity
  table: calendars

  embedded:
    id:
      class: Dende\Calendar\Domain\Calendar\CalendarId
      columnPrefix: ~

  fields:
    name:
      type: string
      nullable: false
      length: 255

  oneToMany:
    events:
      targetEntity: Dende\Calendar\Domain\Calendar\Event
      mappedBy: calendar
      cascade: ["all"]