Dende\Calendar\Domain\Calendar\Event\Occurrence:
  type: entity
  table: occurrences
  repositoryClass: Dende\CalendarBundle\Repository\ORM\OccurrenceRepository

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  embedded:
    duration:
      class: Dende\Calendar\Domain\Calendar\Event\Duration
      columnPrefix: false

  manyToOne:
    event:
      targetEntity: Dende\Calendar\Domain\Calendar\Event
      mappedBy: occurrences
      inversedBy: occurrences

  fields:
    startDate:
      type: datetime
      nullable: false

    endDate:
      type: datetime
      nullable: false

    modified:
      type: boolean


