Dende\Calendar\Domain\Calendar\Event\Occurrence:
  type: mappedSuperclass
  table: occurrences
  repositoryClass: Dende\CalendarBundle\Repository\ORM\OccurrenceRepository
  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  indexes:
    index_dende_occurrences_dates:
      columns:
        - startDate
        - endDate

  embedded:
    duration:
      class: Dende\Calendar\Domain\Calendar\Event\Occurrence\OccurrenceDuration
      columnPrefix: false

  manyToOne: # occurrence is the owning side!
    event:
      targetEntity: Dende\Calendar\Domain\Calendar\Event
      inversedBy: occurrences
      cascade: [all]
      joinColumns:
        EventId:
          name: event_id
          referencedColumnName: id

  fields:
    startDate:
      type: datetime
      nullable: false

    endDate:
      type: datetime
      nullable: false

    modified:
      type: boolean

    deletedAt:
      type: datetime
      nullable: true