Dende\Calendar\Domain\Calendar\Event:
  type: entity
  table: events
  repositoryClass: Dende\CalendarBundle\Repository\ORM\EventRepository

  id:
    id:
      type: guid
      generator: { strategy: UUID }

  embedded:
    type:
      class: Dende\Calendar\Domain\Calendar\Event\EventType
      columnPrefix: false

    repetitions:
      class: Dende\Calendar\Domain\Calendar\Event\Repetitions
      columnPrefix: false

    duration:
      class: Dende\Calendar\Domain\Calendar\Event\Duration
      columnPrefix: false

  manyToOne:
    calendar:
      targetEntity: Dende\Calendar\Domain\Calendar
      inversedBy: events
      cascade: ["all"]

  oneToMany:
    occurrences:
      targetEntity: Dende\Calendar\Domain\Calendar\Event\Occurrence
      mappedBy: event
      cascade: ["all"]

  fields:
    startDate:
      type: datetime
      nullable: false

    endDate:
      type: datetime
      nullable: false

    title:
      type: string
      nullable: false
      length: 255