Dende\Calendar\Domain\Calendar:
  type: entity
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: discriminator
    type: string
  discriminatorMap:
    bundle: Dende\Calendar\Domain\Calendar

  table: calendars
  repositoryClass: Dende\CalendarBundle\Repository\ORM\CalendarRepository

  gedmo:
    soft_deleteable:
      field_name: deletedAt
      time_aware: false


  id:
    id:
      type: guid
      generator: { strategy: UUID }

  fields:
    name:
      type: string
      nullable: false
      length: 255

    deletedAt:
      type: date
      nullable: true

  oneToMany:
    events:
      targetEntity: Dende\Calendar\Domain\Calendar\Event
      mappedBy: calendar
      orphanRemoval: true
      cascade: ["all"]
