---
parameters:
  dende_calendar.id_generator_class: Dende\Calendar\Application\Generator\Doctrine\IdGenerator

services:
  dende_calendar.occurrences_repository:
    class: Dende\CalendarBundle\Repository\ORM\OccurrenceRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: "getRepository"
    arguments: ["Calendar:Calendar\Event\Occurrence"]

  dende_calendar.event_repository:
    class: Dende\CalendarBundle\Repository\ORM\EventRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: "getRepository"
    arguments: ["Calendar:Calendar\Event"]

  dende_calendar.occurrences_provider:
    class: "Dende\CalendarBundle\Service\OccurrencesProvider"
    arguments:
      - @dende_calendar.occurrences_repository
      - @router.default
      - 'dende_calendar_default_updateevent'

  dende_calendar.id_generator:
    class: %dende_calendar.id_generator_class%
    arguments: [@doctrine.orm.entity_manager]

  dende_calendar.factory.calendar:
    class: Dende\Calendar\Application\Factory\CalendarFactory
    arguments:
      - @dende_calendar.id_generator

  dende_calendar.factory.event:
    class: Dende\Calendar\Application\Factory\EventFactory
    arguments:
      - @dende_calendar.id_generator

  dende_calendar.factory.occurrence:
    class: Dende\Calendar\Application\Factory\OccurrenceFactory
    arguments:
      - @dende_calendar.id_generator

  dende_calendar.form_type.create_event:
    class: Dende\CalendarBundle\Form\Type\CreateEventType
    tags:
      - {name: form.type, alias: create_event}

  dende_calendar.form_type.update_event:
    class: Dende\CalendarBundle\Form\Type\UpdateEventType
    tags:
      - {name: form.type, alias: update_event}

  dende_calendar.form_type.calendar:
    class: Dende\CalendarBundle\Form\Type\CalendarType
    tags:
      - {name: form.type, alias: calendar}

  dende_calendar.handler.create_event:
    class: Dende\Calendar\Application\Handler\CreateEventHandler
    arguments:
      - @dende_calendar.event_repository
      - @dende_calendar.occurrences_repository
      - @dende_calendar.factory.event
      - @dende_calendar.factory.occurrence


  dende_calendar.handler.remove_event:
    class: Dende\Calendar\Application\Handler\RemoveEventHandler
    arguments:
      - @dende_calendar.event_repository
  dende_calendar.handler.remove_occurrence:
    class: Dende\Calendar\Application\Handler\RemoveOccurrenceHandler
    arguments:
      - @dende_calendar.occurrences_repository

  dende_calendar.handler.update_event:
    class: Dende\Calendar\Application\Handler\UpdateEventHandler
    calls: # move to compiler pass
      - [addStrategy, ['single', @dende_calendar.update_strategy.single]]
      - [addStrategy, ['overwrite', @dende_calendar.update_strategy.overwrite]]
    arguments:
      - @dende_calendar.event_repository
      - @dende_calendar.occurrences_repository
      - @dende_calendar.factory.event
      - @dende_calendar.factory.occurrence

  dende_calendar.update_strategy.single: # move to compiler pass
    class: Dende\Calendar\Application\Handler\UpdateStrategy\Single
    tags:
      - {name: dende_calendar.update_strategy }

  dende_calendar.update_strategy.overwrite: # move to compiler pass
    class: Dende\Calendar\Application\Handler\UpdateStrategy\Overwrite
    tags:
      - {name: dende_calendar.update_strategy }
