---
services:
  dende_calendar.occurrences_repository:
    class: Dende\CalendarBundle\Repository\ORM\OccurrenceRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: "getRepository"
    arguments: ["Calendar:Calendar\Event\Occurrence"]

  dende_calendar.occurrences_provider:
    class: "Dende\CalendarBundle\Service\OccurrencesProvider"
    arguments:
      - @dende_calendar.occurrences_repository
      - @router.default
      - 'dende_calendar_default_updateevent'

  dende_calendar.id_generator:
    class: Dende\CalendarBundle\Service\IdGenerator
    arguments: [@doctrine.orm.entity_manager]

  dende_calendar.factory.calendar:
    class: Dende\CalendarBundle\Entity\Factory\CalendarFactory
    arguments:
      - @dende_calendar.id_generator

  dende_calendar.form_type.create_event:
    class: Dende\CalendarBundle\Form\Type\CreateEventType
    tags:
      - {name: form.type, alias: create_event}

  dende_calendar.form_type.update_event:
    class: Dende\CalendarBundle\Form\Type\UpdateEventType
    tags:
      - {name: form.type, alias: update_event}