Dende\Calendar\Domain\Calendar\Event:
  type: entity
  table: events
  readOnly: true

  id:
    id:
      type: string

  fields:
    startDate:
      type: datetime

    endDate:
      type: datetime

    title:
      type: string
      length: 255

    type:
      column: type
      type: string
      length: 255

    repetitions:
      column: weekdays
      type: json_array
      length: 255

    duration:
      column: minutes
      type: integer
