Dende\Calendar\Domain\Calendar\Event\Occurrence:
  type: entity
  table: occurrences
  readOnly: true

  id:
    id:
      type: string

  fields:
    startDate:
      type: datetime
      nullable: false

    endDate:
      type: datetime
      nullable: false

    duration:
      column: minutes
      type: integer

    modified:
      type: boolean

  manyToOne:
    event:
      targetEntity: Dende\Calendar\Domain\Calendar\Event
      mappedBy: occurrences
      cascade: ["all"]
      inversedBy: occurrences