Dende\Calendar\Domain\Calendar\Event:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
    title:
      expose: true
    type:
      expose: true
    startDate:
      expose: true
    endDate:
      expose: true
    repetitions:
      expose: true
    duration:
      expose: true
    calendar:
      expose: false
      exclude: true